import GasConfig

translations = {
	"% increment over straight line value": {"es": "% de incremento sobre el valor en línea recta"},
	"{} points along {:.2f} Kms.:":   {"es": "{} puntos a lo largo de {:.2f} Kms.:"},
	"{} stations found (out of {}):": {"es": "{} gasolineras encontradas (de un total de {}):"},
	"{} stations in source data:":	  {"es": "{} gasolineras en la fuente de datos:"},
	" Kms.":				{"es": " Kms."},
	"A gas station finder":	{"es": "Un buscador de gasolineras"},
	"About":				{"es": "Acerca de"},
	"Address":				{"es": "Dirección"},
	"Along route: ":		{"es": "A lo largo de una ruta: "},
	"Around location: ":	{"es": "En torno a un punto: "},
	"Availability (%)":		{"es": "Disponibilidad (%)"},
	"Available fuel types": {"es": "Combustibles disponibles"},
	"Average (€/L)":		{"es": "Promedio (€/L)"},
	"Bad distance correction percentage.": 	{"es": "Porcentaje de corrección de distancia erróneo."},
	"Bad max. distance value.":				{"es": "Valor erróneo para la máxima distancia."},
	"Bad max. oldness value.":				{"es": "Valor erróneo para la máxima antigüedad."},
	"Bad number format.":	{"es": "Formato de úmero erróneo."},
	"Brand":				{"es": "Marca"},
	"Search":				{"es": "Buscar"},
	"Cancel":				{"es": "Cancelar"},
	"Can't access data source. Check URL.": {"es": "No se puede acceder a la fuente de datos. Comprobar la URL."},
	"Can't delete last item in list.": 		{"es": "No se puede borrar el último elemento de la lista."},
	"Can't use character \"(\" in name.":	{"es": "No se puede usar el carácter \"(\" en el nombre."},
	"Choose...":			{"es": "Seleccionar..."},
	"Cons":					{"es": "Cons"},
	"Consumption":			{"es": "Consumo"},
	"Cost (€)":				{"es": "Coste (€)"},
	"Cost breakdown":		{"es": "Desglose del coste"},
	"Cost breakdown information": 	{"es": "Información del desglose del coste"},
	"Data source has changed.": 	{"es": "La fuente de datos ha cambiado."},
	"Directions":					{"es": "Indicaciones"},
	"Distance correction: ": 		{"es": "Corrección de distancia: "},
	"degrees":				{"es": "grados"},
	"Default":				{"es": "Por defecto"},
	"Delete":				{"es": "Borrar"},
	"Discount":				{"es": "Descuento"},
	"Discounts":			{"es": "Descuentos"},
	"Distance (Kms)":		{"es": "Distancia (Kms)"},
	"Downloading data...":	{"es": "Descargando datos..."},
	"Downloaded {} Kbytes...": {"es": "Descargados {} Kbytes..."},
	"Edit":					{"es": "Editar"},
	"English":				{"es": "Inglés"},
	"Exit":					{"es": "Salir"},
	"Error":				{"es": "Error"},
	"Error in Combustivels_PT": 					{"es": "Error en Combustivels_PT"},
	"Error parsing GPX file.":						{"es": "Error al analizar el fichero GPX."},
	"Errors detected, check file \"{}\"":			{"es": "Se han detectado errores, comprobar el fichero \"{}\""},
	"Field can't be empty.":						{"es": "El campo no se puede quedar vacío."},
	"File must have one single track. {} found.": 	{"es": "El fichero debe contener una única pista. Se han encontrado {}."},
	"Found inconsistent {} for id={}.\n":			{"es": "Se encontró {} inconsistente para el id={}.\n"},
	"Fuel": 				{"es": "Combustible"},
	"Fuel price is {:.3f} €/L:": {"es": "El precio del combustible es {:.3f} €/L:"},
	"Fuel type": 			{"es": "Tipo de combustible"},
	"Get new data":			{"es": "Descargar nuevos datos"},
	"File":					{"es": "Fichero"},
	"Gas station finder": 	{"es": "Buscador de gasolineras"},
	"Getting gas stations information": 	{"es": "Obteniendo información de las gasolineras"},
	"GPX files":							{"es": "Ficheros GPX"},
	"GPX file does not exist.": 			{"es": "El fichero GPX no existe."},
	"GPX file information": {"es": "Información del fichero GPX"},
	"Help":					{"es": "Ayuda"},
	"hours":				{"es": "horas"},
	"Info...":				{"es": "Info..."},
	"Initial price is {:.3f} €/L, after discounts it's {:.3f} €/L:": {"es": "El precio inicial es de {:.3f} €/L, tras descuentos queda en {:.3f} €/L:"},
	"Item":					{"es": "Elemento"},
	"L":					{"es": "L"}, 
	"Language: ":			{"es": "Idioma: "},
	"Language has changed, restart is required.": {"es": "El idioma ha cambiado, hay que reinicializar la aplicación."},
	"Lat":					{"es": "Lat"}, 
	"Latitude":				{"es": "Latitud"}, 
	"Licensed under the GNU General Public License": {"es": "Licencia GNU General Public License"},
	"liters":				{"es": "litros"},
	"liters per 100 Kms":	{"es": "litros a los 100 Kms"},
	"Longitude":			{"es": "Longitud"}, 
	"Lon":					{"es": "Lon"}, 
	"Location":				{"es": "Ubicación"},
	"Locations":			{"es": "Ubicaciones"},
	"L/100Kms":				{"es": "L/100Kms"},
	"Max. distance to reference: ": {"es": "Máx. distancia a la referencia: "},
	"Max. oldness in price data: ": {"es": "Máx. antigüedad precios: "},
	"Max. stations to show: ":		{"es": "Máx. número de estaciones a mostrar: "},
	"Maximum (€/L)":		{"es": "Máximo (€/L)"},
	"Minimum (€/L)":		{"es": "Mínimo (€/L)"},
	"Name:":				{"es": "Nombre:"},
	"Name already exists.": {"es": "El nombre ya existe."},
	"New":					{"es": "Crear"},
	"New data will be downloaded on next search.": 	{"es": "Se descargarán nuevos datos en la siguiente búsqueda."},
	"New price data will be downloaded since current data is older than allowed in Setup.": {"es": "Se descargarán nuevos precios ya que los disponibles son más antiguos que lo especificado en Ajustes."},
	"No stations found (out of {})":  			  	{"es": "No se encontraron estaciones (de un total de {})"},
	"Ok":											{"es": "Aceptar"},
	"Pct":					{"es": "Pct"},
	"Percentage":			{"es": "Porcentaje"},
	"Price (€/L)":			{"es": "Precio (€/L)"},
	"Prices to use: ":		{"es": "Precios a usar: "},
	"Profile \"{}\" specifies a fuel type which is not supported in the current price source (\"{}\")": {"es": "El Perfil \"{}\" especifica un tipo de combustible que no está contemplado en la fuente de precios actual (\"{}\")"},
	"Profiles {} specify a fuel type which is not supported in the current price source (\"{}\")": 		{"es": "Los perfiles {} especifican un tipo de combustible que no está contemplado en la fuente de precios actual (\"{}\")"},
	"Profile":				{"es": "Perfil"},
	"Profiles":				{"es": "Perfiles"},
	"Reading {}%...":		{"es": "Leyendo {}%..."},
	"Reading data...":		{"es": "Leyendo datos..."},
	"Reference: ":			{"es": "Referencia: "},
	"Route information":	{"es": "Información de la ruta"},
	"Route point (Kms)":	{"es": "Punto en ruta (Kms)"},
	"Select gpx file":		{"es": "Seleccionar fichero gpx"},
	"Setup":			  	{"es": "Ajustes"},
	"Show brands: ":		{"es": "Mostrar marcas:"},
	"Show on map":			{"es": "Mostrar en el mapa"},
	"Spanish": 				{"es": "Español"},
	"Status code {} on request. Check URL.": {"es": "Código de estado {} al realizar la petición. Comprobar la URL."},
	"Tank":										{"es": "Depósito"},
	"Tank capacity":							{"es": "Capacidad del depósito"},
	"Tank refill:":								{"es": "Repostaje:"},
	"To and from station (2x{:.2f} kms):": 		{"es": "Ida y vuelta a la gasolinera (2x{:.2f} kms):"},
	"Total cost:":								{"es": "Coste total:"},
	"There has been an error processing the source. No data is available.": {"es": "Ha ocurrido un error en la fuente de datos."},
	"Updated":				{"es": "Actualizado"},
	"Use existing data":	{"es": "Usar los últimos datos disponibles"},
	"Value":				{"es": "Valor"},
	"Vehicle profile: ":	{"es": "Perfil del vehículo: "},
	"Warning":				{"es": "Atención"},
	"Waypoint":				{"es": "Punto en ruta"},
}

def Translate(text):
	language = GasConfig.Cfg["Default Language"]
	if language  == "en":
		return text
	else:
		try:
			return translations[text][language]
		except:
			print("GasLangs: {} translation not found for \"{}\"".format(language,text))
			return text
			
def Translations(text):
	return translations[text]
